### ISSUE TITLE
[Question] Issue with my system (The One Ring v1)

### ISSUE THREAD

**Issue by herveDarritchon** [JDR-Ninja/foundryvtt-dice-cheater-protector#1]
Hi,

One of my user has also your module to avoir dice cheating and I think my code and yours are a kind of incompatible.
I'd like to have your opinion.

Foundry VTT : 0.7.9

In the console, there is an error when your module is active.

```log
tor1e.mjs:17 Uncaught (in promise) TypeError: Cannot assign to read only property 'rolls' of object '#<Object>'
    at tor1e.mjs:17
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at Game.initialize (foundry.js:6457)
    at window.addEventListener.once (foundry.js:7449)
(anonymous) @ tor1e.mjs:17
_call @ foundry.js:2496
callAll @ foundry.js:2456
initialize @ foundry.js:6457
window.addEventListener.once @ foundry.js:7449
async function (async)
window.addEventListener.once @ foundry.js:7448
```

In my code, the line 17 of the tor1e.mjs is :

`    CONFIG.Dice.rolls = [...CONFIG.Dice.rolls, Tor1eRoll];`

I think it looks like your module can't modify the `CONFIG.Dice`

I'd like your point of view about this.

Thanks.

**Comment by JDR-Ninja** [comment]
Sorry for the delay, I am not familiar with github! My module "freeze" the method for avoid modification and change the random method.
I will update my code today and the user can now select if the random function is modified or not.

**Comment by JDR-Ninja** [comment]
I see the problem, I freeze then entire object **CONFIG.Dice**. I'll see what I can do. Like moving the freeze after all the other modules.

**Comment by herveDarritchon** [comment]
> Sorry for the delay, I am not familiar with github! My module "freeze" the method for avoid modification and change the random method.
> I will update my code today and the user can now select if the random function is modified or not.

No worry, nice to answer anyway :D

I have found a workaround to my issue

```js
// Define custom Roll class (change with attention because of compatibility issue with Dice Cheater Protector module)
    CONFIG.Dice.rolls.push(CONFIG.Dice.rolls[0]);
    CONFIG.Dice.rolls[0] = Tor1eRoll;
```

but indeed if you can fix this issue, it would be great asI think it would be nicer. 

But for  those who have this issue, I propose a workaround above ;)

**Comment by JDR-Ninja** [comment]
With the 0.1.1 I changed the initialization method. Now I use a better (and recommended) method:
```js
Hooks.once('ready', () => {
```
In my first version I used
```js
(() => {

})();
```
In this way there is no more conflict.
I called this code on line 40 of tor1e.mjs and it now returns false when my module is activated.
```js
console.log('isFrozen ' + Object.isFrozen(CONFIG.Dice));
```
My module is now initialized in the READY state of the game. :)
