### ISSUE TITLE
Does this mod need anything to work in V10?

### ISSUE THREAD

**Issue by galaara98** [JDR-Ninja/foundryvtt-dice-cheater-protector#3]
just wondering if this should work in v10 (nothing is erroring, but not sure if it is working)

**Comment by EndlessFractal** [comment]
Still working as intended!

In other news:

I tweaked my main.js a bit to provide even more randomness!

The getCryptoRandom on the main.js only provides 32 bits of randomness.

[This solution](https://stackoverflow.com/a/34577886) bumps it up to 52 bits: 

```
function getCryptoRandom() {
    let buffer = new ArrayBuffer(8);
    let ints = new Int8Array(buffer);
    window.crypto.getRandomValues(ints);
    ints[7] = 63;
    ints[6] |= 0xf0;
    let float = new DataView(buffer).getFloat64(0, true) - 1;
    return float;
    // https://stackoverflow.com/a/34577886
}
```

**Comment by EndlessFractal** [comment]
I made an updated release! Feel free to check it!

https://github.com/NotoriusNeo/foundryvtt-dice-rng-protector/releases/latest

**Comment by JDR-Ninja** [comment]
@NotoriusNeo  That's excellent. I just explored the different commits on your branch and I would like to incorporate them.
 Can you make a pull request?

**Comment by JDR-Ninja** [comment]
I will release an update this week with NotoriusNeo commits. :)
