### ISSUE TITLE
Invalid manifest for version 10.291

### ISSUE THREAD

**Issue by Kilrathisly** [JDR-Ninja/foundryvtt-dice-cheater-protector#6]
cannot install or update . invalid manifest error in FoundryVTT
![Screenshot 2023-06-18 131417](https://github.com/JDR-Ninja/foundryvtt-dice-cheater-protector/assets/41693197/edc04080-875d-4afb-82ca-3e13d4b42ea4)

**Comment by JDR-Ninja** [comment]
I prepare the V12 support version.
